# Exported from:        http://DESKTOP-LS62RGN:5516/
# Release version:      25.1.1-512.313
# Date created:         Mon Sep 29 21:37:54 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Connections.yaml
  - Notifications.yaml
  - Template_temp1.yaml
